
package CMSC495_TT;
/**
 *
 * @author Manoj
 */
/*  Tenacious Turtles Team
    Apparel Point of Sale (APOS) system
    Transaction Form
    This is GUI for sales/returns transaction.  This is part 
    of presentation layer.  So not much buisiness logic
    in this class except form control logics.

    This form uses javax.swing features.

*/
import cmsc495_tt_phase2.*;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.tree.DefaultTreeCellEditor;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.KeyStroke;
import java.util.*;



 public class TransactionForm extends javax.swing.JFrame {
    private Transaction transObj = new Transaction();
    private Employee employeeObj;
    
    // Edit Listeners on transaction item table
    CellEditorListener UpcChange = new CellEditorListener() {
        public void editingCanceled(ChangeEvent e) {
        }
       public void editingStopped(ChangeEvent e) {
           UpcChanged();
       }   
    };
 
      CellEditorListener UnitsChange = new CellEditorListener() {
        public void editingCanceled(ChangeEvent e) {
       }
       public void editingStopped(ChangeEvent e) {
          UnitsChanged();
       }   
    };

    /**
     * Creates new form TransactionForm
     */
      
    // Default constructor
    public TransactionForm() {
        initComponents();
    }
    // Constructor with employee object parameter
    public TransactionForm(Employee employeeObjIn) {
        this.employeeObj = employeeObjIn;
        this.transObj = new Transaction(employeeObj);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        transTypeSales = new javax.swing.JRadioButton();
        transTypeReturns = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblStoreNum = new javax.swing.JLabel();
        lblStoreAddress = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jLabel13 = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblDesignation = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        button4 = new java.awt.Button();
        subTotal1 = new javax.swing.JFormattedTextField();
        taxAmount = new javax.swing.JFormattedTextField();
        gTotal = new javax.swing.JFormattedTextField();
        totalUnits = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        transTable = new SkipColumnTable();
        button3 = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        paymentType = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        button5 = new java.awt.Button();
        receiptForReturns = new java.awt.TextField();
        storeCreditNumber = new java.awt.TextField();
        setReturn = new java.awt.Button();
        transactionNumber = new javax.swing.JTextField();
        storeCreditAmtFld = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cashAmtFld = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transacton Type: ");

        jLabel2.setText("Sub Total:");

        jLabel3.setText("Tax:");

        jLabel4.setText("Total:");

        buttonGroup1.add(transTypeSales);
        transTypeSales.setText("Sales");
        transTypeSales.setToolTipText("");
        transTypeSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transTypeSalesMouseClicked(evt);
            }
        });
        transTypeSales.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                transTypeSalesStateChanged(evt);
            }
        });
        transTypeSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transTypeSalesActionPerformed(evt);
            }
        });

        buttonGroup1.add(transTypeReturns);
        transTypeReturns.setText("Returns");
        transTypeReturns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transTypeReturnsMouseClicked(evt);
            }
        });
        transTypeReturns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transTypeReturnsActionPerformed(evt);
            }
        });

        jLabel6.setText("Store:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tenacious Turtles Clothing Company");

        lblStoreNum.setText("10001");

        lblStoreAddress.setText("1234 Main Street, Adelphi, MD 20783");

        jLabel10.setText("Receipt# for returns:");

        jLabel11.setText("Transaction Number (Receipt Number): ");

        button1.setActionCommand("buttonLogOut");
        button1.setLabel("Log-out");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Store Employee:");

        lblEmployeeName.setText("Dan Edmonston");

        jLabel15.setText("Designation:");

        lblDesignation.setText("Sales Associate");

        button2.setActionCommand("buttonCompleteTrans");
        button2.setLabel("Complete Transaction");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button4.setActionCommand("buttonInvLookup");
        button4.setLabel("Inventory Lookup");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        subTotal1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        subTotal1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        subTotal1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        subTotal1.setEnabled(false);

        taxAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        taxAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        taxAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taxAmount.setEnabled(false);

        gTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        gTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gTotal.setEnabled(false);

        totalUnits.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        totalUnits.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalUnits.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        totalUnits.setEnabled(false);

        transTable.setModel(transObj.getTransModelObj());
        transTable.setColumnSelectionAllowed(true);
        transTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        transTable.setEditingColumn(0);
        transTable.setEditingRow(0);
        transTable.setFillsViewportHeight(true);
        transTable.setFocusCycleRoot(true);
        transTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(transTable);
        transTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        transTable.getDefaultEditor (String.class).addCellEditorListener(UpcChange);
        transTable.getDefaultEditor (Integer.class).addCellEditorListener(UnitsChange);
        transTable.getColumnModel().getColumn(9).setCellRenderer(new CurrencyTableCellRenderer());
        transTable.getColumnModel().getColumn(7).setCellRenderer(new CurrencyTableCellRenderer());
        lblEmployeeName.setText (transObj.employeeObj.getFirstName() + " " + transObj.employeeObj.getLastName());
        lblDesignation.setText (transObj.employeeObj.getDesignation());
        lblStoreNum.setText (String.valueOf(transObj.getEmployeeObj().getStoreNum()));
        lblStoreAddress.setText (transObj.getStoreObj().getFullAddress());
        transTypeSales.setSelected (true);
        transTypeReturns.setSelected (false);
        transactionNumber.setText (String.valueOf(transObj.getTransNum()));
        paymentType.setEnabled (true);
        storeCreditNumber.setEnabled (true);
        storeCreditAmtFld.setEnabled (true);
        receiptForReturns.setEnabled (false);
        setReturn.setEnabled (false);

        button3.setActionCommand("buttonTransRpt");
        button3.setLabel("Transaction Report");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Payment Type:");

        paymentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Store Credit" }));
        paymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTypeActionPerformed(evt);
            }
        });

        jLabel9.setText("Store Credit Number:");

        button5.setActionCommand("buttonClearTrans");
        button5.setLabel("Clear Transaction");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        receiptForReturns.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                receiptForReturnsTextValueChanged(evt);
            }
        });
        receiptForReturns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptForReturnsActionPerformed(evt);
            }
        });
        receiptForReturns.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                receiptForReturnsFocusLost(evt);
            }
        });
        receiptForReturns.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                receiptForReturnsCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                receiptForReturnsInputMethodTextChanged(evt);
            }
        });

        storeCreditNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeCreditNumberActionPerformed(evt);
            }
        });

        setReturn.setActionCommand("setReturn");
        setReturn.setLabel("Set Returns");
        setReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setReturnActionPerformed(evt);
            }
        });

        transactionNumber.setEnabled(false);
        transactionNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionNumberActionPerformed(evt);
            }
        });

        storeCreditAmtFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        storeCreditAmtFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        storeCreditAmtFld.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setText("StoreCredit Amt:");

        cashAmtFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        cashAmtFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashAmtFld.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cashAmtFld.setEnabled(false);

        jLabel12.setText("Cash Amt:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblStoreNum))
                                    .addComponent(lblStoreAddress))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(transTypeSales)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(receiptForReturns, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(setReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))
                                    .addComponent(transTypeReturns)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(transactionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(storeCreditNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(155, 155, 155)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(totalUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(storeCreditAmtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cashAmtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(transTypeSales)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(lblStoreNum)
                        .addComponent(jLabel10)
                        .addComponent(jLabel13)
                        .addComponent(lblEmployeeName))
                    .addComponent(receiptForReturns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transTypeReturns)
                    .addComponent(lblStoreAddress)
                    .addComponent(jLabel15)
                    .addComponent(lblDesignation))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addComponent(storeCreditNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(subTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(transactionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeCreditAmtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashAmtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        button3.getAccessibleContext().setAccessibleName("buttonTransRpt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed
//  Complete transaction action
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        transObj.setPaymentType(String.valueOf(paymentType.getSelectedItem()));
        String msgStr = transObj.transactionCompleted();
        
        transObj.clearTransaction();
        // Clear controls on form
        ClearTransactionOnForm();
        transTable.setModel(transObj.getTransModelObj());
        transTable.getColumnModel().getColumn(9).setCellRenderer(new CurrencyTableCellRenderer());
        transTable.getColumnModel().getColumn(7).setCellRenderer(new CurrencyTableCellRenderer());
        transObj.getNewTransNum();
        transactionNumber.setText(String.valueOf(transObj.getTransNum()));

        paymentType.setEnabled(true);
        storeCreditNumber.setEnabled(true);
        storeCreditAmtFld.setEnabled(true);
        taxAmount.setValue(0);
        gTotal.setValue(0);
        subTotal1.setValue(0);
        totalUnits.setValue(0);
        receiptForReturns.setText("");
        paymentType.setSelectedIndex(0);
        transTypeSales.setSelected(true);
        transTypeReturns.setSelected(false);
        transObj.setTransType("Sales");
        storeCreditNumber.setText("");
       
        
        
        
    }//GEN-LAST:event_button2ActionPerformed
    // Log-out button logic
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        LogInForm logIn = new LogInForm();
        logIn.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed
    // Creating return transaction itesms from a previous sales receipt
    private void transTypeSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transTypeSalesActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_transTypeSalesActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:  
        ReportForm rptFrm = new ReportForm();
        rptFrm.setVisible(true);
               
    }//GEN-LAST:event_button3ActionPerformed

    private void paymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTypeActionPerformed
    // Clearing transaction for new 
    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        transObj.clearTransaction();
        ClearTransactionOnForm();
        transTable.setModel(transObj.getTransModelObj());
        transTable.getColumnModel().getColumn(9).setCellRenderer(new CurrencyTableCellRenderer());
        transTable.getColumnModel().getColumn(7).setCellRenderer(new CurrencyTableCellRenderer());
        
    }//GEN-LAST:event_button5ActionPerformed

    private void transTypeReturnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transTypeReturnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transTypeReturnsActionPerformed

    private void receiptForReturnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptForReturnsActionPerformed
  
    }//GEN-LAST:event_receiptForReturnsActionPerformed

    private void storeCreditNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeCreditNumberActionPerformed

    }//GEN-LAST:event_storeCreditNumberActionPerformed

    private void receiptForReturnsTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_receiptForReturnsTextValueChanged
    }//GEN-LAST:event_receiptForReturnsTextValueChanged

    private void receiptForReturnsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_receiptForReturnsFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptForReturnsFocusLost

    private void receiptForReturnsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_receiptForReturnsInputMethodTextChanged
    }//GEN-LAST:event_receiptForReturnsInputMethodTextChanged

    private void receiptForReturnsCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_receiptForReturnsCaretPositionChanged
        
    }//GEN-LAST:event_receiptForReturnsCaretPositionChanged
    // Creating return transaction items from original sales receipt number
    private void setReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setReturnActionPerformed
        if (transObj.getTransType() == "Returns") {
            paymentType.setSelectedIndex(0);
            transObj.setPaymentType("Cash");
            transObj.setReturnsFromPreviousSales(Integer.valueOf(receiptForReturns.getText()));
            transTable.setModel(transObj.getTransModelObj());
            transTable.getColumnModel().getColumn(9).setCellRenderer(new CurrencyTableCellRenderer());
            transTable.getColumnModel().getColumn(7).setCellRenderer(new CurrencyTableCellRenderer());
            taxAmount.setValue(transObj.getTaxAmount());
            gTotal.setValue(transObj.getTotAmount());
            subTotal1.setValue(transObj.getMerchAmount());
            totalUnits.setValue(transObj.getTotUnits());
            storeCreditNumber.setText("");
            storeCreditAmtFld.setValue(0);
            cashAmtFld.setValue(0);
            storeCreditAmtFld.setEditable(false);
       } else 
       {
            String msgStr = "Error 2.3 This operation is not allowed for Sales transaction";
            JOptionPane.showMessageDialog(this, msgStr);
            receiptForReturns.setText("");
       }
        
    }//GEN-LAST:event_setReturnActionPerformed

    private void transTypeSalesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_transTypeSalesStateChanged
        // TODO add your handling code here:
                  
    }//GEN-LAST:event_transTypeSalesStateChanged
    // Sales transaction selected 
    private void transTypeSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transTypeSalesMouseClicked
        if (transTypeSales.isSelected()) {
        transObj.setTransType(transTypeSales.getText());
        transObj.clearTransaction();
        ClearTransactionOnForm();
        transTable.setModel(transObj.transModelObj);
        transTable.getColumnModel().getColumn(9).setCellRenderer(new CurrencyTableCellRenderer());
        transTable.getColumnModel().getColumn(7).setCellRenderer(new CurrencyTableCellRenderer());
        paymentType.setSelectedIndex(0);
        paymentType.setEnabled(true);
        storeCreditNumber.setEnabled(true);
        storeCreditAmtFld.setEnabled(true);
        storeCreditAmtFld.setEditable(true);
        receiptForReturns.setEnabled(false);
        setReturn.setEnabled(false);
        
        }
    }//GEN-LAST:event_transTypeSalesMouseClicked
    // REturns transaction selected
    private void transTypeReturnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transTypeReturnsMouseClicked
        if (transTypeReturns.isSelected()) {
        transObj.setTransType("Returns");
        transObj.clearTransaction();
        ClearTransactionOnForm();
        transObj.setPaymentType("Store Credit");
        storeCreditNumber.setText(String.valueOf(transObj.getTransNum()));
        transTable.setModel(transObj.transModelObj);
        transTable.getColumnModel().getColumn(9).setCellRenderer(new CurrencyTableCellRenderer());
        transTable.getColumnModel().getColumn(7).setCellRenderer(new CurrencyTableCellRenderer());
        paymentType.setSelectedIndex(1);
        paymentType.setEnabled(false);
        storeCreditNumber.setEnabled(false);
        storeCreditAmtFld.setEnabled(false);
        receiptForReturns.setEnabled(true);
        setReturn.setEnabled(true);
        }

    }//GEN-LAST:event_transTypeReturnsMouseClicked

    private void transactionNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionNumberActionPerformed
    // UPC Change: set transaction item values
    public void UpcChanged() {
        String msgStr = "";
        int rw = transTable.getSelectedRow();
        int cl = transTable.getSelectedColumn();
        Object upc = transTable.getValueAt(rw, cl);
        String upcCode = upc.toString();
        msgStr = transObj.upcChanged(rw, cl, upcCode);
        if (msgStr != "")
            JOptionPane.showMessageDialog(this, msgStr);
     
    }
    // Units Change: run method in transaction and reset values on form
    public void UnitsChanged() {
        String msgStr = "";
        System.out.println("Coming here");
        
        int rw = transTable.getSelectedRow();
        int cl = transTable.getSelectedColumn();
   
        int units =  (int)(transTable.getValueAt(rw, cl));
        msgStr = transObj.unitsChanged(rw, cl, units);
        if (msgStr != "") {
          JOptionPane.showMessageDialog(this, msgStr);  
        }
        else 
        {
        subTotal1.setValue(transObj.getMerchAmount());
        taxAmount.setValue(transObj.getTaxAmount());
        gTotal.setValue(transObj.getTotAmount());
        totalUnits.setValue(transObj.getTotUnits());
        cashAmtFld.setValue(transObj.getCashPayAmt());
        storeCreditAmtFld.setValue(transObj.getStoreCreditPayAmt());
        
        
        }
    }
    // Clear transaction on form
    public void ClearTransactionOnForm() {
        taxAmount.setValue(0);
        gTotal.setValue(0);
        subTotal1.setValue(0);
        totalUnits.setValue(0);
        receiptForReturns.setText("");
        paymentType.setSelectedIndex(0);
        cashAmtFld.setValue(0);
        storeCreditAmtFld.setValue(0);
        storeCreditNumber.setText("");
    
        
    }
               
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField cashAmtFld;
    private javax.swing.JFormattedTextField gTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblStoreAddress;
    private javax.swing.JLabel lblStoreNum;
    private javax.swing.JComboBox paymentType;
    private java.awt.TextField receiptForReturns;
    private java.awt.Button setReturn;
    private javax.swing.JFormattedTextField storeCreditAmtFld;
    private java.awt.TextField storeCreditNumber;
    private javax.swing.JFormattedTextField subTotal1;
    private javax.swing.JFormattedTextField taxAmount;
    private javax.swing.JFormattedTextField totalUnits;
    private javax.swing.JTable transTable;
    private javax.swing.JRadioButton transTypeReturns;
    private javax.swing.JRadioButton transTypeSales;
    private javax.swing.JTextField transactionNumber;
    // End of variables declaration//GEN-END:variables
}
